/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gw.com.sistema.view;

import com.formdev.flatlaf.FlatDarkLaf;
import gw.com.sistema.dao.AlunoDAO;
import gw.com.sistema.model.Aluno;
import gw.com.sistema.utilitarios.Utilitarios;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author giova
 */
public class CadastrarAluno extends javax.swing.JFrame {
    private JProgressBar progressBar;

    /**
     * Creates new form CadastrarAluno
     */
    public void listar() {
        AlunoDAO dao = new AlunoDAO();
        List<Aluno> lista = dao.listar();
        DefaultTableModel model = (DefaultTableModel) tabela_Alunos.getModel();
        model.setNumRows(0);
        for(Aluno al : lista) {
            model.addRow(new Object[] {
                al.getId(),
                al.getNome(),
                al.getCodigo(),
                al.getEmail(),
                al.getCurso(),
                al.getNivel(),
                al.getContacto(),
            });
        }
    }
    
    public CadastrarAluno() {
        initComponents();
        setLocationRelativeTo(null);
        txtNome.requestFocus();
        
        progressBar = new JProgressBar();
        progressBar.setIndeterminate(true);
        progressBar.setVisible(false);

        getContentPane().add(progressBar, java.awt.BorderLayout.SOUTH);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        painel_guias = new javax.swing.JTabbedPane();
        painel_dados_pessoais = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnPesquisarCadastro = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtContacto = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCurso = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbNivel = new javax.swing.JComboBox<>();
        painel_lista = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JTextField();
        btnPesquisarLista = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_Alunos = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtCodigo1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Aluno");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(30, 30, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Aluno");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(42, 42, 42))
        );

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gw/com/sistema/imagens/novo.png"))); // NOI18N
        btnNovo.setText("NOVO");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gw/com/sistema/imagens/slavar.png"))); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gw/com/sistema/imagens/editar.png"))); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gw/com/sistema/imagens/eliminar.png"))); // NOI18N
        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        painel_guias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                painel_guiasKeyPressed(evt);
            }
        });

        painel_dados_pessoais.setBackground(new java.awt.Color(30, 30, 30));
        painel_dados_pessoais.setFocusTraversalPolicyProvider(true);
        painel_dados_pessoais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                painel_dados_pessoaisKeyReleased(evt);
            }
        });

        jLabel3.setText("ID:");

        txtId.setEditable(false);

        jLabel4.setText("Nome:");

        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
        });

        btnPesquisarCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gw/com/sistema/imagens/pesquisar.png"))); // NOI18N
        btnPesquisarCadastro.setText("PESQUISAR");
        btnPesquisarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarCadastroActionPerformed(evt);
            }
        });

        jLabel5.setText("E-mail:");

        jLabel6.setText("Contacto:");

        try {
            txtContacto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(+245) ###-###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactoActionPerformed(evt);
            }
        });

        jLabel7.setText("Código:");

        try {
            txtCodigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel8.setText("Curso:");

        txtCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCursoActionPerformed(evt);
            }
        });

        jLabel9.setText("Nível:");

        cbNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1ºAno", "2ºAno", "3ºAno", "4ºAno" }));

        javax.swing.GroupLayout painel_dados_pessoaisLayout = new javax.swing.GroupLayout(painel_dados_pessoais);
        painel_dados_pessoais.setLayout(painel_dados_pessoaisLayout);
        painel_dados_pessoaisLayout.setHorizontalGroup(
            painel_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_dados_pessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_dados_pessoaisLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_dados_pessoaisLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisarCadastro))
                    .addGroup(painel_dados_pessoaisLayout.createSequentialGroup()
                        .addGroup(painel_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painel_dados_pessoaisLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painel_dados_pessoaisLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        painel_dados_pessoaisLayout.setVerticalGroup(
            painel_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_dados_pessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarCadastro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        painel_guias.addTab("CADASTRAR", painel_dados_pessoais);

        painel_lista.setBackground(new java.awt.Color(30, 30, 30));

        jLabel2.setText("Nome:");

        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });

        btnPesquisarLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gw/com/sistema/imagens/pesquisar.png"))); // NOI18N
        btnPesquisarLista.setText("PESQUISAR");
        btnPesquisarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarListaActionPerformed(evt);
            }
        });

        tabela_Alunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Codigo", "E-mail", "Curso", "Nivel", "Contacto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_Alunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_AlunosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabela_AlunosMousePressed(evt);
            }
        });
        tabela_Alunos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabela_AlunosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_Alunos);
        if (tabela_Alunos.getColumnModel().getColumnCount() > 0) {
            tabela_Alunos.getColumnModel().getColumn(0).setPreferredWidth(20);
            tabela_Alunos.getColumnModel().getColumn(2).setPreferredWidth(20);
            tabela_Alunos.getColumnModel().getColumn(5).setPreferredWidth(30);
        }

        jLabel10.setText("Codigo:");

        javax.swing.GroupLayout painel_listaLayout = new javax.swing.GroupLayout(painel_lista);
        painel_lista.setLayout(painel_listaLayout);
        painel_listaLayout.setHorizontalGroup(
            painel_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_listaLayout.createSequentialGroup()
                .addGroup(painel_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(painel_listaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisarLista))
                    .addGroup(painel_listaLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        painel_listaLayout.setVerticalGroup(
            painel_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_listaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarLista)
                    .addComponent(jLabel10)
                    .addComponent(txtCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painel_guias.addTab("LISTA", painel_lista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(btnNovo)
                .addGap(12, 12, 12)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painel_guias)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painel_guias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
            if (tabela_Alunos.getSelectedRowCount() == 1) {
            Aluno obj = new Aluno();
            obj.setId(Integer.parseInt(txtId.getText()));
            AlunoDAO dao = new AlunoDAO();
            dao.Excluir(obj);
            Utilitarios util = new Utilitarios();
            util.LimparTela(painel_dados_pessoais);
            txtNome.requestFocus();
        }else {
                JOptionPane.showMessageDialog(null, "Selecione uma linha!");
            }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCursoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        
        if (txtNome.getText().isEmpty() ||
            txtCodigo.getText().isEmpty() ||
            txtEmail.getText().isEmpty() ||
            txtCurso.getText().isEmpty() ||
            txtContacto.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "PREENCHA TODOS OS CAMPOS!");
            return;
        }

        // Desativa botão e mostra loading
        btnSalvar.setEnabled(false);
        progressBar.setVisible(true);

        // Cria o objeto Aluno
        Aluno obj = new Aluno();
        obj.setNome(txtNome.getText());
        obj.setCodigo(Integer.parseInt(txtCodigo.getText()));
        obj.setEmail(txtEmail.getText());
        obj.setCurso(txtCurso.getText());
        obj.setNivel((String) cbNivel.getSelectedItem());
        obj.setContacto(txtContacto.getText());

        // SwingWorker
        new SwingWorker<Boolean, Void>() {

            @Override
            protected Boolean doInBackground() {
                try {
                    AlunoDAO dao = new AlunoDAO();
                    dao.Salvar(obj); // acesso ao banco
                    return true;
                } catch (Exception e) {
                    e.printStackTrace();
                    return false;
                }
            }

            @Override
            protected void done() {
                progressBar.setVisible(false);
                btnSalvar.setEnabled(true);

                try {
                    if (get()) {
                        JOptionPane.showMessageDialog(null, "Aluno salvo com sucesso!");
                    } else {
                        JOptionPane.showMessageDialog(null, "Erro ao salvar aluno!");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro inesperado!");
                }
            }

        }.execute();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        listar();
    }//GEN-LAST:event_formWindowActivated

    private void btnPesquisarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarCadastroActionPerformed
        // TODO add your handling code here:
        String nome = txtNome.getText();
        Aluno obj = new Aluno();
        AlunoDAO dao = new AlunoDAO();
        
        obj = dao.Buscar_Aluno(nome);
        if (obj.getNome() != null) {
            txtId.setText(String.valueOf(obj.getId()));
            txtNome.setText(obj.getNome());
            txtCodigo.setText(String.valueOf(obj.getCodigo()));
            txtEmail.setText(obj.getEmail());
            txtCurso.setText(obj.getCurso());
            cbNivel.setSelectedItem(obj.getNivel());
            txtContacto.setText(obj.getContacto());
        } else {
            JOptionPane.showMessageDialog(null, "Aluno não encontrado!");
        }
    }//GEN-LAST:event_btnPesquisarCadastroActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        Utilitarios util = new Utilitarios();
        util.LimparTela(painel_dados_pessoais);
        txtNome.requestFocus();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnPesquisarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarListaActionPerformed
        // TODO add your handling code here:
        
        if (txtPesquisar.getText().isEmpty() && txtCodigo1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite um nome ou um código!");
            return;
        }

        String nome = "%" + txtPesquisar.getText() + "%";

        int codigo = 0;
        if (!txtCodigo1.getText().isEmpty()) {
            codigo = Integer.parseInt(txtCodigo1.getText());
        }

        AlunoDAO dao = new AlunoDAO();
        List<Aluno> lista = dao.filtrar(nome, codigo);

        DefaultTableModel model = (DefaultTableModel) tabela_Alunos.getModel();
        model.setNumRows(0);

        for (Aluno al : lista) {
            model.addRow(new Object[] {
                al.getId(),
                al.getNome(),
                al.getCodigo(),
                al.getEmail(),
                al.getCurso(),
                al.getNivel(),
                al.getContacto(),
            });
        }
    }//GEN-LAST:event_btnPesquisarListaActionPerformed

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        // TODO add your handling code here:
        if (txtPesquisar.getText().isEmpty() && txtCodigo1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite um nome ou um código!");
            return;
        }

        String nome = "%" + txtPesquisar.getText() + "%";

        int codigo = 0;
        if (!txtCodigo1.getText().isEmpty()) {
            codigo = Integer.parseInt(txtCodigo1.getText());
        }

        AlunoDAO dao = new AlunoDAO();
        List<Aluno> lista = dao.filtrar(nome, codigo);

        DefaultTableModel model = (DefaultTableModel) tabela_Alunos.getModel();
        model.setNumRows(0);

        for (Aluno al : lista) {
            model.addRow(new Object[] {
                al.getId(),
                al.getNome(),
                al.getCodigo(),
                al.getEmail(),
                al.getCurso(),
                al.getNivel(),
                al.getContacto(),
            });
        }
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void painel_dados_pessoaisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_painel_dados_pessoaisKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_painel_dados_pessoaisKeyReleased

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String nome = txtNome.getText();
            Aluno obj = new Aluno();
            AlunoDAO dao = new AlunoDAO();

            obj = dao.Buscar_Aluno(nome);
            if (obj.getNome() != null) {
                txtId.setText(String.valueOf(obj.getId()));
                txtNome.setText(obj.getNome());
                txtCodigo.setText(String.valueOf(obj.getCodigo()));
                txtEmail.setText(obj.getEmail());
                txtCurso.setText(obj.getCurso());
                cbNivel.setSelectedItem(obj.getNivel());
                txtContacto.setText(obj.getContacto());
            } else {
                JOptionPane.showMessageDialog(null, "Aluno não encontrado!");
            }
        }
    }//GEN-LAST:event_txtNomeKeyPressed

    private void tabela_AlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_AlunosMouseClicked
        // TODO add your handling code here:

            painel_guias.setSelectedIndex(0);
            txtId.setText(tabela_Alunos.getValueAt(tabela_Alunos.getSelectedRow(), 0).toString());
            txtNome.setText(tabela_Alunos.getValueAt(tabela_Alunos.getSelectedRow(), 1).toString());
            txtCodigo.setText(tabela_Alunos.getValueAt(tabela_Alunos.getSelectedRow(), 2).toString());
            txtEmail.setText(tabela_Alunos.getValueAt(tabela_Alunos.getSelectedRow(), 3).toString());
            txtCurso.setText(tabela_Alunos.getValueAt(tabela_Alunos.getSelectedRow(), 4).toString());
            cbNivel.setSelectedItem(tabela_Alunos.getValueAt(tabela_Alunos.getSelectedRow(), 5).toString());
            txtContacto.setText(tabela_Alunos.getValueAt(tabela_Alunos.getSelectedRow(), 6).toString());

    }//GEN-LAST:event_tabela_AlunosMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
            Aluno obj = new Aluno();
            obj.setNome(txtNome.getText());
            obj.setCodigo(Integer.parseInt(txtCodigo.getText()));
            obj.setEmail(txtEmail.getText());
            obj.setCurso(txtCurso.getText());
            obj.setNivel((String) cbNivel.getSelectedItem());
            obj.setContacto(txtContacto.getText());
            obj.setId(Integer.parseInt(txtId.getText()));

            AlunoDAO dao = new AlunoDAO();
            dao.Editar(obj);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void tabela_AlunosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabela_AlunosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabela_AlunosKeyPressed

    private void painel_guiasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_painel_guiasKeyPressed
        // TODO add your handling code here:
        if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_L) {
            painel_guias.setSelectedIndex(1);
        } else if(evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_C) {
            painel_guias.setSelectedIndex(0);
        }
    }//GEN-LAST:event_painel_guiasKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void tabela_AlunosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_AlunosMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tabela_AlunosMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatDarkLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisarCadastro;
    private javax.swing.JButton btnPesquisarLista;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbNivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painel_dados_pessoais;
    public javax.swing.JTabbedPane painel_guias;
    private javax.swing.JPanel painel_lista;
    private javax.swing.JTable tabela_Alunos;
    private javax.swing.JFormattedTextField txtCodigo;
    private javax.swing.JTextField txtCodigo1;
    private javax.swing.JFormattedTextField txtContacto;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
