/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Cadastro;





import java.sql.*;
import ConexaoDAO.Conexao;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sistemagestaobiblioteca.Principal;


/**
 *
 * @author Bobito
 */
public class Cadastro extends javax.swing.JDialog {
// PARA LIMPAR CAMPO
    //conexao= (Connection) Conexao.Conectar();
      
    public void Limpar(){
    
  CampoTitulo.setText("");
  CampoAutor.setText("");
  Publicar.setDate(null);
   CampoEditora .setText("");
   CampoIdioma.setSelectedIndex(0);
   CampoDiscrição.setText("");
   CampoGenero.setSelectedIndex(0);
   CampoGenero.setSelectedIndex(0);
   DataEntrada.setDate(null);
   CampoPagina.setValue(0);
    }
    
    
    /**
     * Creates new form Cadastro
     */
    public Cadastro(java.awt.Frame parent, boolean modal) throws ClassNotFoundException {
        super(parent, modal);
        initComponents();
          setLocationRelativeTo(null);
          Connection conexao=Conexao.getConnection();
            FlatMacLightLaf.setup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CampoTitulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CampoAutor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CampoEditora = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CampoIdioma = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        CampoDiscrição = new javax.swing.JEditorPane();
        jLabel8 = new javax.swing.JLabel();
        CampoGenero = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        DataEntrada = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        CampoCondição = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Publicar = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        CampoPagina = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SISTEMA DE GESTÃO DE BIBLIOTECA");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemagestaobiblioteca/LIVROS_GRANDE.png"))); // NOI18N
        jLabel1.setText("Cadastar");

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel2.setText("Titulo");

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel4.setText("Autor");

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel5.setText("Ano de Publicação");

        jLabel6.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel6.setText("Editora");

        CampoEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoEditoraActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel7.setText("Idioma");

        CampoIdioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "Criolo", "Olof", "latim", "Egipcio", "Português", "Inglês", "Espanhol", "Francês", "Alemão", "Italiano", "Russo", "Chinês (Mandarim)", "Japonês", "Coreano", "Árabe", "Hindi", "Bengali", "Turco", "Grego", "Hebraico", "Sueco", "Norueguês", "Dinamarquês", "Holandês", "Polonês", "Tcheco", "Romeno", "Húngaro", "Tailandês", "Vietnamita", "Malaio", "Indonésio", "Filipino (Tagalog)", "Swahili" }));

        jScrollPane1.setViewportView(CampoDiscrição);

        jLabel8.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel8.setText("Descrição");

        CampoGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   ", "Romance", "Conto", "Novela", "Fantasia", "Ficção científica", "Distopia/Utopia", "Suspense/Thriller", "Policial/Crime", "Terror/Horror", "Romance histórico", "Romance de época", "Romance contemporâneo", "Biografia/Autobiografia", "Memórias", "Ensaios", "História", "Ciência/Divulgação científica", "Autoajuda/Desenvolvimento pessoal", "Religião/Espiritualidade", "Política/Sociologia", "Poesia", "Teatro/Drama", "Literatura infantil", "Young Adult (YA)", "Educativo", "Graphic novel/Quadrinhos" }));

        jLabel9.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel9.setText("Data de Entrada");

        jLabel10.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel10.setText("Genero");

        jLabel11.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel11.setText("Condição");

        CampoCondição.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "    ", "Novo", "Seminovo", "Usado", "Raro", "Esgotado", "De colecionador", "Primeira edição", "Autografado", "Em bom estado", "Em estado regular", "Em mau estado" }));
        CampoCondição.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCondiçãoActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 204, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemagestaobiblioteca/10_97263.png"))); // NOI18N
        jButton1.setText("LIMPAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 204, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemagestaobiblioteca/Salvar.png"))); // NOI18N
        jButton3.setText("SALVAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel12.setText("Numero de Pagina");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CampoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(CampoAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addComponent(jLabel3)
                                    .addComponent(Publicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10)
                                    .addComponent(CampoIdioma, 0, 154, Short.MAX_VALUE)
                                    .addComponent(jLabel7)
                                    .addComponent(CampoEditora, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addComponent(jLabel6)
                                    .addComponent(CampoGenero, 0, 0, Short.MAX_VALUE))
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9)
                                    .addComponent(DataEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11)
                                    .addComponent(CampoCondição, 0, 162, Short.MAX_VALUE)
                                    .addComponent(jLabel12)
                                    .addComponent(CampoPagina))))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CampoEditora, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(CampoTitulo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addComponent(jLabel11)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoCondição, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(DataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CampoGenero, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(CampoPagina)
                    .addComponent(Publicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 
        if (
            CampoTitulo.getText().isEmpty() ||
            CampoAutor.getText().isEmpty() ||
            Publicar.getDate()==null ||
            CampoEditora.getText().isEmpty()||
            CampoIdioma.getSelectedItem()==null||
            CampoGenero.getSelectedItem()==null ||
            DataEntrada.getDate()==null ||
            CampoCondição.getSelectedItem()==null ||
            CampoDiscrição.getText().isEmpty() ||
            (CampoPagina.getValue()==null || (Integer)CampoPagina.getValue()<=0)
        ) {
            JOptionPane.showMessageDialog(null,"Os campos não podem ser nulo ou vazio");
        }else{
            LIVROS a=new LIVROS();

            a.setTitulo(CampoTitulo.getText());
            a.setAutor(CampoAutor.getText());
            a.setAnoPublico(new java.sql.Date(Publicar.getDate().getTime()));
            a.setEditora(CampoEditora.getText());
            a.setIdioma((String) CampoIdioma.getSelectedItem());
            a.setGenero((String) CampoGenero.getSelectedItem());
            a.setDataEntrada(new java.sql.Date(DataEntrada.getDate().getTime()));
            a.setCondição((String) CampoCondição.getSelectedItem());
            a.setDescrição(CampoDiscrição.getText());
            a.setNumeroPagina((Integer)CampoPagina.getValue());
            Principal a1=new Principal();
            a1.chamarTabela();
            try{
                Enviar b=new Enviar();
                b.inserir(a);

            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,"Não guardado " + ex);

            }
        }
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Limpar()     ;   // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CampoCondiçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCondiçãoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCondiçãoActionPerformed

    private void CampoEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoEditoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoEditoraActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
       FlatMacLightLaf.setup();
        //</editor-fold>
 
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Cadastro dialog = new Cadastro(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoAutor;
    private javax.swing.JComboBox<String> CampoCondição;
    private javax.swing.JEditorPane CampoDiscrição;
    private javax.swing.JTextField CampoEditora;
    private javax.swing.JComboBox<String> CampoGenero;
    private javax.swing.JComboBox<String> CampoIdioma;
    private javax.swing.JSpinner CampoPagina;
    private javax.swing.JTextField CampoTitulo;
    private com.toedter.calendar.JDateChooser DataEntrada;
    private com.toedter.calendar.JDateChooser Publicar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
