/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TelaBem_Vinda;

import ConexaoDAO.Conexao;
import Login.Login;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author Bobito
 */
public class Tela_Bem_Vinda extends javax.swing.JFrame {
Connection conexao=null;
ResultSet rs=null;
PreparedStatement pst=null;
  
/**
     
     * Creates new form Tela_Bem_Vinda
     */
    public Tela_Bem_Vinda() throws ClassNotFoundException {
        initComponents();

        setLocationRelativeTo(null);
           setIconImage(new ImageIcon(getClass().getResource("Icon.png")).getImage());
        setTitle("SISTEMA DE GESTÃO DE BIBLIOTECA");
        conexao=Conexao.getConnection();
        System.out.println(conexao);
         FlatMacLightLaf.setup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        Progresso = new javax.swing.JProgressBar();
        Percentagem = new javax.swing.JLabel();
        Infor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jLayeredPane1.add(Progresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 350, 20));

        Percentagem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Percentagem.setText("0%");
        jLayeredPane1.add(Percentagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));

        Infor.setText("Carregando...");
        jLayeredPane1.add(Infor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TelaBem_Vinda/FUNDO_BV.png"))); // NOI18N
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException {
        
        //</editor-fold>
FlatMacLightLaf.setup(); 
    Tela_Bem_Vinda A=new Tela_Bem_Vinda();
        A.setVisible(true);
     FlatMacLightLaf.setup();
        try{
        for(int a=0;a<=100;a++){
        Thread.sleep(100);
        A.Percentagem.setText(a+"%");
        if(a==30){
         A.Infor.setText("Buscando...");
        }
        if(a==60){
         A.Infor.setText("Conectando...");
        }
         if(a==100){
         A.Infor.setText("A Abrir...");
        }
      A.Progresso.setValue(a);
        }
      FlatMacLightLaf.setup();
      Login L=new Login();
      L.setVisible(true);
      A.setVisible(false);
        }catch(Exception e){
        JOptionPane.showMessageDialog(null,"O progresso negado");}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Infor;
    private javax.swing.JLabel Percentagem;
    private javax.swing.JProgressBar Progresso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
