/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemagestaobiblioteca;

import Cadastro.Enviar;
import Cadastro.LIVROS;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.PrintJob;
import java.awt.Toolkit;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Bobito
 */
public class Atualizar extends javax.swing.JFrame implements Printable {

    /**
     * Creates new form Atualizar
     */
    public Atualizar() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        CampoId = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        CampoT = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        CampoA = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        CampoEditora = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        CampoIdioma = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        CampoDiscrição = new javax.swing.JEditorPane();
        jLabel44 = new javax.swing.JLabel();
        CampoGenero = new javax.swing.JComboBox<>();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        DataEntrada = new com.toedter.calendar.JDateChooser();
        jLabel47 = new javax.swing.JLabel();
        CampoCondição = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        Publicar = new com.toedter.calendar.JDateChooser();
        jLabel48 = new javax.swing.JLabel();
        CampoPa = new javax.swing.JSpinner();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel37.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel37.setText("Informação de Livro:");

        jLabel38.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel38.setText("Titulo");

        jLabel39.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N

        jLabel40.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel40.setText("Autor");

        jLabel41.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel41.setText("Ano de Publicação");

        jLabel42.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel42.setText("Editora");

        CampoEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoEditoraActionPerformed(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel43.setText("Idioma");

        CampoIdioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "Criolo", "Olof", "latim", "Egipcio", "Português", "Inglês", "Espanhol", "Francês", "Alemão", "Italiano", "Russo", "Chinês (Mandarim)", "Japonês", "Coreano", "Árabe", "Hindi", "Bengali", "Turco", "Grego", "Hebraico", "Sueco", "Norueguês", "Dinamarquês", "Holandês", "Polonês", "Tcheco", "Romeno", "Húngaro", "Tailandês", "Vietnamita", "Malaio", "Indonésio", "Filipino (Tagalog)", "Swahili" }));

        jScrollPane4.setViewportView(CampoDiscrição);

        jLabel44.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel44.setText("Descrição");

        CampoGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   ", "Romance", "Conto", "Novela", "Fantasia", "Ficção científica", "Distopia/Utopia", "Suspense/Thriller", "Policial/Crime", "Terror/Horror", "Romance histórico", "Romance de época", "Romance contemporâneo", "Biografia/Autobiografia", "Memórias", "Ensaios", "História", "Ciência/Divulgação científica", "Autoajuda/Desenvolvimento pessoal", "Religião/Espiritualidade", "Política/Sociologia", "Poesia", "Teatro/Drama", "Literatura infantil", "Young Adult (YA)", "Educativo", "Graphic novel/Quadrinhos" }));

        jLabel45.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel45.setText("Data de Entrada");

        jLabel46.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel46.setText("Genero");

        jLabel47.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel47.setText("Condição");

        CampoCondição.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "    ", "Novo", "Seminovo", "Usado", "Raro", "Esgotado", "De colecionador", "Primeira edição", "Autografado", "Em bom estado", "Em estado regular", "Em mau estado" }));
        CampoCondição.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCondiçãoActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 204, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemagestaobiblioteca/10_97263.png"))); // NOI18N
        jButton7.setText("DELETAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(0, 204, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemagestaobiblioteca/refresh_arrow_1546.png"))); // NOI18N
        jButton8.setText("ATUALIZAR");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel48.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel48.setText("Numero de Pagina");

        jButton9.setBackground(new java.awt.Color(0, 204, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemagestaobiblioteca/Printer_26276.png"))); // NOI18N
        jButton9.setText("IMPRIMIR");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemagestaobiblioteca/LOGO2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel44)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CampoT)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel41)
                                    .addComponent(jLabel40)
                                    .addComponent(CampoA)
                                    .addComponent(jLabel39)
                                    .addComponent(Publicar, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel46)
                                    .addComponent(CampoIdioma, 0, 154, Short.MAX_VALUE)
                                    .addComponent(jLabel43)
                                    .addComponent(CampoEditora)
                                    .addComponent(jLabel42)
                                    .addComponent(CampoGenero, 0, 0, Short.MAX_VALUE))
                                .addGap(52, 52, 52)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel45)
                                    .addComponent(DataEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel47)
                                    .addComponent(CampoCondição, 0, 162, Short.MAX_VALUE)
                                    .addComponent(jLabel48)
                                    .addComponent(CampoPa)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(jLabel37)))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37)
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jLabel42)
                    .addComponent(jLabel45))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CampoEditora, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(CampoT))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel40))
                            .addComponent(jLabel47)
                            .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoCondição, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(DataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(jLabel46)
                    .addComponent(jLabel48))
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CampoGenero, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(CampoPa)
                    .addComponent(Publicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton7)
                    .addComponent(jButton9))
                .addGap(19, 19, 19))
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("ASSINATURA DO ADMINSTARDOR");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(256, 5));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(197, 197, 197))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(173, 173, 173))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoEditoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoEditoraActionPerformed

    private void CampoCondiçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCondiçãoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCondiçãoActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        if (CampoId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite o ID!");
            return;
        }

        try {
            int id = Integer.parseInt(CampoId.getText());

            LIVROS a = new LIVROS();
            a.setId(id);

            Principal dao = new Principal();
            dao.ApagarAT(a);

            JOptionPane.showMessageDialog(null, "Registo apagado com sucesso!");
            this.dispose();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ID inválido!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao apagar!");
            System.out.println("Erro: " + e);
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (CampoT.getText().isEmpty()
                || CampoA.getText().isEmpty()
                || Publicar.getDate() == null
                || CampoEditora.getText().isEmpty()
                || CampoIdioma.getSelectedItem() == null
                || CampoGenero.getSelectedItem() == null
                || DataEntrada.getDate() == null
                || CampoCondição.getSelectedItem() == null
                || CampoDiscrição.getText().isEmpty()
                || (CampoPa.getValue() == null || (Integer) CampoPa.getValue() <= 0)) {
            JOptionPane.showMessageDialog(null, "Os campos não podem ser nulo ou vazio");
        } else {
            LIVROS a = new LIVROS();

            a.setTitulo(CampoT.getText());
            a.setAutor(CampoA.getText());
            a.setAnoPublico(new java.sql.Date(Publicar.getDate().getTime()));
            a.setEditora(CampoEditora.getText());
            a.setIdioma((String) CampoIdioma.getSelectedItem());
            a.setGenero((String) CampoGenero.getSelectedItem());
            a.setDataEntrada(new java.sql.Date(DataEntrada.getDate().getTime()));
            a.setCondição((String) CampoCondição.getSelectedItem());
            a.setDescrição(CampoDiscrição.getText());
            a.setNumeroPagina((Integer) CampoPa.getValue());
            a.setId(Integer.parseInt(CampoId.getText()));

            Principal a1 = new Principal();
            a1.chamarTabela1();

            try {
                Enviar aw = new Enviar();
                aw.Atualizar(a);
                JOptionPane.showMessageDialog(null, "Registo atualizado com sucesso");
                a1.chamarTabela();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Não Atualizado " + ex);

            }
        }

        // TODO add your handling code here:

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        PrinterJob imprimir = PrinterJob.getPrinterJob();
        imprimir.setPrintable(this);
        if(imprimir.printDialog()){
            try {
                imprimir.print();
            } catch (PrinterException ex) {
            }
        }else{
        JOptionPane.showMessageDialog(this,"A imprssao nao efetuado");
        }
        
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

        FlatMacLightLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Atualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField CampoA;
    public javax.swing.JComboBox<String> CampoCondição;
    public javax.swing.JEditorPane CampoDiscrição;
    public javax.swing.JTextField CampoEditora;
    public javax.swing.JComboBox<String> CampoGenero;
    public javax.swing.JTextField CampoId;
    public javax.swing.JComboBox<String> CampoIdioma;
    public javax.swing.JSpinner CampoPa;
    public javax.swing.JTextField CampoT;
    public com.toedter.calendar.JDateChooser DataEntrada;
    public com.toedter.calendar.JDateChooser Publicar;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
        if (pageIndex == 0) {
            Graphics2D G2D=(Graphics2D)graphics;
            G2D.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
            printAll(G2D);
            return PAGE_EXISTS;
        } else {
            return NO_SUCH_PAGE;
        }
    }
}
