/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

/**
 *
 * @author Bobito
 */

import ConexaoDAO.Conexao;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import sistemagestaobiblioteca.Principal;

public class Login extends javax.swing.JFrame {
    

    Connection conexao = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    

    public void Envar() {
        String sql = "select * from usuario where Nome = ? and Senha = ?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, CampoNome.getText());
            pst.setString(2, CampoSenha.getText());
            rs = pst.executeQuery();

            if (rs.next()) {
                Principal vg= new Principal();
               vg. setVisible(true);
               // fechar ao chamar tela principal
               this.dispose();
             
                

            } else {
                JOptionPane.showMessageDialog(null, "Senha ou nome invalido");
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro " + e.getMessage());
        }finally{
        if(conexao!=null){
            try {
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"conexao nao fechou");
            }
}
        }
    }

    /**
     * Creates new form Login
     */
    public Login() throws ClassNotFoundException {
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("Icon.png")).getImage());
        setTitle("SISTEMA DE GESTÃO DE BIBLIOTECA");
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        conexao=Conexao.getConnection();
        System.out.println(conexao);
         FlatMacLightLaf.setup();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L = new javax.swing.JLabel();
        CampoNome = new javax.swing.JTextField();
        CampoSenha = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        Senha = new javax.swing.JLabel();
        Enviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        L.setForeground(new java.awt.Color(0, 153, 255));
        L.setText("------FAÇA LOGIN-----");
        getContentPane().add(L, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        CampoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNomeActionPerformed(evt);
            }
        });
        getContentPane().add(CampoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 180, -1));
        getContentPane().add(CampoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 180, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setText("Nome");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        Senha.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Senha.setText("Senha");
        getContentPane().add(Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        Enviar.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Enviar.setForeground(new java.awt.Color(0, 102, 153));
        Enviar.setText("Enviar");
        Enviar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 2));
        Enviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarActionPerformed(evt);
            }
        });
        getContentPane().add(Enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 70, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/FundoLogin.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CampoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNomeActionPerformed

    private void EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarActionPerformed
       Envar() ; // TODO add your handling code here:
    }//GEN-LAST:event_EnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        //</editor-fold>
        
    FlatMacLightLaf.setup();      
                
                
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
                   

            public void run() {
                try {
                    new Login().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
                
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoNome;
    private javax.swing.JPasswordField CampoSenha;
    private javax.swing.JButton Enviar;
    private javax.swing.JLabel L;
    private javax.swing.JLabel Senha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
